# Generated by Django 3.0.3 on 2020-03-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceTag',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
    ]
