FROM linaro/tensorflow-arm-neoverse-n1:2.3.0-eigen

USER root

RUN apt-get update
RUN apt install -y npm && npm install -g npm@latest-6 n && n 14.15

WORKDIR /app/backend
COPY backend/requirements.txt requirements.txt
RUN pip install -r requirements.txt
WORKDIR /app/angular-front
COPY angular-front/package.json package.json
RUN npm install -g @angular/cli@8.3.25 && npm install 

WORKDIR /app
COPY angular-front angular-front
RUN cd angular-front && ng build
COPY backend backend
ENTRYPOINT python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8080
