# Generated by Django 3.0.2 on 2020-02-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.BigIntegerField(unique=True)),
                ('text', models.TextField()),
                ('screen_name', models.TextField()),
                ('retweeted', models.BooleanField()),
                ('user_image_url', models.TextField()),
            ],
        ),
    ]
