# Generated by Django 3.0.3 on 2020-03-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweettopic_api', '0002_tweet_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='topic',
            field=models.TextField(default=None, null=True),
        ),
    ]
